<?php

/**
 * @file
 * Contains spotify.module.
 */

 use Drupal\Core\Routing\RouteMatchInterface;

 function spotify_permission() {

   return array(
        'access content' => array(
            'title' => t('Acceso a Spotify'),
            'description' => t('Permite la visualización del modulo de Spotify'),
        ),
    );

 }

 function spotify_theme($existing, $type, $theme, $path) {
  return array(
    'spotify_artist' => array(
      'variables' => array('artist' => array() , 'albums' => array())
    ),
    'spotify_tracks' => array(
      'variables' => array( 'tracks' => array())
    ),
  );
}
